openapi: 3.0.1
info:
  title: Test schemas
  description: Test schemas for parquet-json
  version: 1.0.0
servers:
  - url: 'https://getyourguide.com'
paths: {}
components:
  schemas:
    TestPrimitives:
      title: TestPrimitives
      type: object
      properties:
        key_string:
          type: string
          nullable: false
        key_int32:
          type: integer
          format: int32
          nullable: true
        key_int64:
          type: integer
          format: int64
          nullable: true
        key_float:
          type: number
          format: float
          nullable: true
        key_double:
          type: number
          format: double
          nullable: true
        is_true:
          type: boolean
          nullable: true
        date:
          type: string
          format: date
          nullable: true
        datetime:
          type: string
          format: date-time
          nullable: true
      example:
        key_string: hello
        key_int32: 32
        key_int64: 64
        key_float: 10.1
        key_double: 10.101
        is_true: true
        date: '2020-06-20'
        datetime: '2020-06-20T10:10:10.000Z'
    TestArraysPrimitives:
      title: TestArraysPrimitives
      type: object
      properties:
        array_string:
          nullable: true
          type: array
          items:
            type: string
        array_int:
          type: array
          items:
            type: integer
            format: int64
            nullable: true
        array_bool:
          type: array
          nullable: true
          items:
            type: boolean
            nullable: true
      example:
        array_string:
          - hello
          - bonjour
          - gruezi
          - hallo
    TestArraysOfObjects:
      title: "TestArraysOfObjects"
      type: object
      properties:
        array_key:
          type: array
          items:
            type: object
            properties:
              key_a:
                type: string
              key_b:
                type: string
      example:
        array_key:
          - key_a: "hello"
            key_b: "goodbye"
          - key_a: "bonjour"
            key_b: "aurevoir"
    TestNestedStructure:
      title: TestNestedStructure
      type: object
      properties:
        simple_key:
          type: integer
          nullable: true
        simple_nested:
          type: object
          title: simple_nested
          properties:
            key1:
              type: string
              format: date
            key2:
              type: array
              items:
                type: integer
      example:
        simple_nested:
          key1: '2020-06-20'
          key2: [1, 2, 3]
    TestDeeperNestedStructure:
      title: TestDeeperNestedStructure
      type: object
      properties:
        1st_level_key1:
          type: string
          nullable: true
        1st_level_key_nested:
          type: object
          properties:
            key1:
              type: object
              properties:
                key1_key1:
                  type: string
                  nullable: true
                key1_key2:
                  type: string
                  nullable: true
            key2:
              type: string
              nullable: true
      example:
        1st_level_key1: Hello
        1st_level_key_nested:
          key1:
            key1_key1: Bonjour
            key1_key2: Guten Tag!
          key2: Olla!
    TestMapStructure:
      title: TestMapStructure
      type: object
      properties:
        map_key:
          type: object
          additionalProperties:
            type: array
            items:
              type: integer
      example:
        map_key:
          key1: [1, 2, 3]
          key2: [4, 5, 6]
    TestMapStructureofObject:
      title: TestMapStructureofObject
      type: object
      properties:
        map_key:
          type: object
          additionalProperties:
            type: object
            properties:
              name:
                type: string
              text:
                type: string
      example:
        map_key:
          en:
            name: "english"
            text: "hello"
          de:
            name: "german"
            text: "hallo"
